### PR TITLE
#12833 solve os related line ending issue

### LINKED ISSUE #12833: Line ending issue in external email facade test
### Bug Description

There are some tests failing dou to line break encoding unix vs win

### Reproduction Steps

1.Run the test in `ExternalEmailFacadeEjbTest`

`testSendEmailToCasePerson` and `testSendEmailToContactPerson` fails

### Expected Behavior

Test should not fail

### Affected Area(s)

Web app

### SORMAS Version

1.93.0-SNAPSHOT

### Android version/Browser

Test Runner

### User Role(s)

Any user

### Server URL

_No response_

### Additional Information

See comment: https://github.com/SORMAS-Foundation/SORMAS-Project/pull/12828#discussion_r1426662899

### PR DESCRIPTION
**Pull request by carina29**
Fixes #12833

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12837

File: sormas-backend/src/test/java/de/symeda/sormas/backend/docgeneration/TemplateTestUtil.java [hunk 1]
```diff
@@ -51,4 +51,13 @@ public static void writeJsonProperty(Object object) throws JsonProcessingExcepti
 	public static String cleanLineSeparators(String text) {
 		return text.replaceAll("\\r\\n?", "\n");
 	}
+
+	public static String addOSBasedLineSeparators(String text) {
```
Comment (MateStrysewske) [inline sormas-backend/src/test/java/de/symeda/sormas/backend/docgeneration/TemplateTestUtil.java:55]:
```suggestion
	public static String updateLineSeparatorsBasedOnOS(String text) {
```

Because the method doesn't add line separators, but merely replaces them (if at all), "add" is not a good method name here

**Review by MateStrysewske — CHANGES_REQUESTED** [review]

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12837

**Comment by MateStrysewske** [comment]
@carina29 I would like to @leventegal-she have the final look at this PR; looks good from my side, but approval should come from him.

**Review by MateStrysewske — APPROVED** [review]

**Review by leventegal-she — APPROVED** [review]
