### PR TITLE
#12661 - Checkbox trees don't trigger unsaved changes warning and can…

### LINKED ISSUE #12661: Checkbox trees don't trigger unsaved changes warning and can't be discarded
### Bug Description

Changes made to the checkboxes for 'Weather conditions at time of sampling' are not considered for the triggering of the 'Confirm navigation' pop-up and are not discarded when the user clicks 'Discard' at the bottom of the page.

### Reproduction Steps

I - 'Confirm navigation' pop-up not triggered:
1. Log in with an Environmental Surveillance User;
2. Open an existing environment sample;
3. Check some of the checkboxes from 'Weather conditions at time of sampling';
4. Click to navigate to any other page in the app.
**Actual behavior:** The confirm navigation pop-up is not triggered by unsaved changes made to the checkboxes.

II - Changes made are not discarded:
1. Log in with an Environmental Surveillance User;
2. Open an existing environment sample;
3. Check some of the checkboxes from 'Weather conditions at time of sampling';
4. Click 'Discard' at the bottom of the page.
**Actual behavior:** The changes made to the checkboxes are not discarded.

### Expected Behavior

Expected behavior for scenario I: Any unsaved change on the environment sample page, including to the checkboxes, should trigger the 'Confirm navigation' pop-up when the user tries to navigate to another page of the app.

Expected behavior for scenario II: Any unsaved changes at the time when the user clicks 'Discard' should be discarded.

### Affected Area(s)

Web app

### SORMAS Version

1.90.0, 1.89.0

### Android version/Browser

Chrome

### User Role(s)

Environmental Surveillance User

### Server URL

local machine 

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by sergiupacurariu**
…'t be discarded

Fixes #12661

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13015

File: sormas-api/src/main/java/de/symeda/sormas/api/environment/WaterUse.java [hunk 1]
```diff
@@ -4,13 +4,23 @@
...
-	UNKNOWN;
+	DRINKING_HOUSEHOLD_NEEDS(null),
+	RECREATION(null),
+	INDUSTRY_COMMERCE(null),
+	AGRICULTURE(null),
+	THERMOELECTRICITY_ENERGY(null),
+	OTHER(null),
+	UNKNOWN(null);
+
+	private WaterUse parent;
```
Comment (leventegal-she) [inline sormas-api/src/main/java/de/symeda/sormas/api/environment/WaterUse.java:15]: parent is useless since none of the elements have a parent. please delete it

File: sormas-api/src/main/java/de/symeda/sormas/api/event/EpidemiologicalEvidenceDetail.java [hunk 2]
```diff
@@ -23,6 +23,12 @@ public enum EpidemiologicalEvidenceDetail {
     STUDY(null),
     CASE_CONTROL_STUDY(STUDY),
     COHORT_STUDY(STUDY),
+    TEST_SERGIU1(COHORT_STUDY),
```
Comment (leventegal-she) [inline sormas-api/src/main/java/de/symeda/sormas/api/event/EpidemiologicalEvidenceDetail.java:26]: please delete test items

File: sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java [hunk 3]
```diff
@@ -1657,39 +1621,19 @@ private void updateFollowUpStatusComponents() {
...
-		reinfectionTrees.values().forEach(t -> {
-			if (t.getValues() != null) {
-				reinfectionDetails.putAll(t.getValues());
-			}
-		});
-		return reinfectionDetails;
-	}
-
 	@Override
 	public CaseDataDto getValue() {
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java:1625]: please delete these method becaus there is no more need to set the reinfection field separately

File: sormas-ui/src/main/java/de/symeda/sormas/ui/environment/EnvironmentDataForm.java [hunk 4]
```diff
@@ -229,29 +228,25 @@ protected void addFields() {
...
-	private boolean isWaterUseOtherChecked() {
-		return Boolean.TRUE.equals(waterUseCheckBoxTree.getValues().get(WaterUse.OTHER));
-	}
-
-	private CheckBoxTree.CheckBoxElement<WaterUse> environmentEvidenceDetailToCheckBoxElement(WaterUse waterUse) {
-		return new CheckBoxTree.CheckBoxElement<>(null, waterUse);
-	}
-
 	@Override
 	public void setValue(EnvironmentDto newFieldValue) throws ReadOnlyException {
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/environment/EnvironmentDataForm.java:241]: get/set should not be needed

File: sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataForm.java [hunk 5]
```diff
@@ -725,15 +696,15 @@ public void setTypeOfPlaceTextRequirement() {
 	@Override
 	public EventDto getValue() {
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataForm.java:697]: this method should not be needed

File: sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataForm.java [hunk 6]
```diff
@@ -725,15 +696,15 @@ public void setTypeOfPlaceTextRequirement() {
...
+		eventDto.setLaboratoryDiagnosticEvidenceDetails(laboratoryDiagnosticEvidenceDetailCheckBoxTreeUpdated.getValue());
 		return eventDto;
 	}
 
 	@Override
 	public void setValue(EventDto newFieldValue) throws ReadOnlyException, Converter.ConversionException {
-		epidemiologicalEvidenceCheckBoxTree.setValues(newFieldValue.getEpidemiologicalEvidenceDetails());
-		laboratoryDiagnosticEvidenceCheckBoxTree.setValues(newFieldValue.getLaboratoryDiagnosticEvidenceDetails());
+		epidemiologicalEvidenceCheckBoxTreeUpdated.setValue(newFieldValue.getEpidemiologicalEvidenceDetails());
+		laboratoryDiagnosticEvidenceDetailCheckBoxTreeUpdated.setValue(newFieldValue.getLaboratoryDiagnosticEvidenceDetails());
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataForm.java:707]: these lines should not be needed

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java [hunk 7]
```diff
@@ -0,0 +1,240 @@
...
+			return checkBoxTreeLayout;
+		}
+
+		return checkBoxTreeLayoutForGroups;
+	}
+
+	private void addGroups() {
+		final ENUM[] enumElements = enumType.getEnumConstants();
+
+		Map<Enum, List<ENUM>> enumGroupMap = new HashMap<>();
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java:96]: please use the Stream api to create the groups

e.g. `.collect(groupingBy(....)`

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java [hunk 8]
```diff
@@ -0,0 +1,240 @@
...
+		for (int i = 0; i < columns; i++) {
+			final VerticalLayout e = new VerticalLayout();
+			e.setMargin(false);
+			e.setSpacing(false);
+			columnList.add(e);
+		}
+
+		AtomicInteger currentColumn = new AtomicInteger();
+		currentColumn.set(0);
+		enumGroupMap.entrySet().stream().forEach(enumListEntry -> {
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java:119]: please change into an indexe for instead of foreach and using an AtomicInteger

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java [hunk 9]
```diff
@@ -0,0 +1,240 @@
...
+
+			if (currentColumn.get() == columns - 1) {
+				currentColumn.set(0);
+			} else {
+				currentColumn.getAndIncrement();
+			}
+		});
+
+		for (int i = 0; i < columns; i++) {
+			checkBoxTreeLayoutForGroups.addComponent(columnList.get(i));
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java:138]: columns can be added right after creation, there is no neeed for another cycle for adding them to tha layout

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java [hunk 10]
```diff
@@ -0,0 +1,240 @@
...
+			enumToggles.put(enumElement, elementCheckbox);
+			checkBoxTreeLayout.addComponent(elementCheckbox);
+		}
+	}
+
+	private int getEnumElementLevel(ENUM enumElement, int level) {
+		ENUM parentElement = parentProvider.apply(enumElement);
+		if (parentElement != null) {
+			level++;
+			return getEnumElementLevel(parentElement, level);
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java:167]: please merge these lines: `return getEnumElementLevel(parentElement, level + 1);`

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java [hunk 11]
```diff
@@ -0,0 +1,240 @@
...
+		} else {
+			return level;
+		}
+	}
+
+	@NotNull
+	private CheckBox createCheckbox(int level, ENUM element, ENUM parentElement) {
+		CheckBox elementCheckbox = new CheckBox(element.toString());
+		final int minLevel = Math.min(level - 1, INDENTATION_STYLES.length - 1);
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java:176]: please rename to safeLevel

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java [hunk 12]
```diff
@@ -0,0 +1,240 @@
...
+			CssStyles.style(elementCheckbox, CssStyles.VSPACE_4);
+		}
+
+		elementCheckbox.setWidth(100, Unit.PERCENTAGE);
+		elementCheckbox.addValueChangeListener(e -> {
+			final Boolean value = (Boolean) e.getProperty().getValue();
+			Map<ENUM, Boolean> newValue = new HashMap<>();
+			if (getValue() != null) {
+				newValue = new HashMap<>(getValue());
+			}
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java:190]: please change the above into a ternary

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java [hunk 13]
```diff
@@ -0,0 +1,240 @@
...
+				final MarginInfo marginInfo = new MarginInfo(false, false, true, false);
+				checkBoxTreeLayout.setMargin(marginInfo);
+			} else {
+				checkBoxTreeLayoutForGroups = new HorizontalLayout();
+				checkBoxTreeLayoutForGroups.setMargin(false);
+				checkBoxTreeLayoutForGroups.setWidth(100, Unit.PERCENTAGE);
+				addGroups();
+			}
+
+			settingToggles = true;
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java:68]: please move changing `settingToggles` into setToggleValues, so it will be done for all cases you call `setToggleValues`

**Review by leventegal-she — CHANGES_REQUESTED** [review]

File: sormas-api/src/main/java/de/symeda/sormas/api/environment/WaterUse.java (hunk 1 above)
Comment (sergiupacurariu) [reply sormas-api/src/main/java/de/symeda/sormas/api/environment/WaterUse.java]: removed

File: sormas-api/src/main/java/de/symeda/sormas/api/event/EpidemiologicalEvidenceDetail.java (hunk 2 above)
Comment (sergiupacurariu) [reply sormas-api/src/main/java/de/symeda/sormas/api/event/EpidemiologicalEvidenceDetail.java:26]: removed

File: sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java (hunk 3 above)
Comment (sergiupacurariu) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java:1626]: removed

File: sormas-ui/src/main/java/de/symeda/sormas/ui/environment/EnvironmentDataForm.java (hunk 4 above)
Comment (sergiupacurariu) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/environment/EnvironmentDataForm.java:242]: removed

File: sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataForm.java (hunk 5 above)
Comment (sergiupacurariu) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataForm.java:697]: removed

File: sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataForm.java (hunk 6 above)
Comment (sergiupacurariu) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataForm.java:707]: removed

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java (hunk 11 above)
Comment (sergiupacurariu) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java:188]: renamed

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java (hunk 13 above)
Comment (sergiupacurariu) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java:70]: create a method and replaced the code

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java (hunk 10 above)
Comment (sergiupacurariu) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java:179]: lines merged

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13015

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java (hunk 9 above)
Comment (sergiupacurariu) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java:142]: moved

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java (hunk 7 above)
Comment (sergiupacurariu) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java:102]: changed approach

File: sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java [hunk 14]
```diff
@@ -181,6 +176,7 @@ public class CaseDataForm extends AbstractEditForm<CaseDataDto> {
 	private static final String REINFECTION_DETAILS_COL_1_LOC = "reinfectionDetailsCol1Loc";
 	private static final String REINFECTION_DETAILS_COL_2_LOC = "reinfectionDetailsCol2Loc";
 	public static final String CASE_REFER_POINT_OF_ENTRY_BTN_LOC = "caseReferFromPointOfEntryBtnLoc";
+	public static final String TEST_Heading = "testHeading";
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java:179]: please remove or rename if still used

File: sormas-ui/src/main/java/de/symeda/sormas/ui/environment/EnvironmentDataForm.java [hunk 15]
```diff
@@ -66,7 +65,7 @@ public class EnvironmentDataForm extends AbstractEditForm<EnvironmentDto> {
 			fluidRowLocs(EnvironmentDto.OTHER_DELETION_REASON);
     //@formatter:on
 
-	private WaterUseCheckBoxTree waterUseCheckBoxTree;
+	CheckBoxTreeUpdated<WaterUse> waterUseCheckBoxTreeUpdated;
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/environment/EnvironmentDataForm.java:68]: this field is useless

File: sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java [hunk 16]
```diff
@@ -1657,39 +1622,10 @@ private void updateFollowUpStatusComponents() {
...
-						newFieldValue.getReinfectionDetails()
-							.entrySet()
-							.stream()
-							.filter(e -> e.getKey().getGroup() == group)
-							.collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue)));
-			} else {
-				reinfectionTrees.get(group).setValues(null);
-			}
-		}
+		reinfectionDetailGroupCheckBoxTreeUpdated.setValue(newFieldValue.getReinfectionDetails());
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java:1628]: remove

File: sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java [hunk 17]
```diff
@@ -316,7 +309,7 @@ public class CaseDataForm extends AbstractEditForm<CaseDataDto> {
 	private FollowUpPeriodDto expectedFollowUpPeriodDto;
 	private boolean ignoreDifferentPlaceOfStayJurisdiction = false;
 
-	private final Map<ReinfectionDetailGroup, CaseReinfectionCheckBoxTree> reinfectionTrees = new EnumMap<>(ReinfectionDetailGroup.class);
+	private CheckBoxTreeUpdated<ReinfectionDetail> reinfectionDetailGroupCheckBoxTreeUpdated;
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java:312]: this field seems to be useless, please convert it to local variable

File: sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataForm.java [hunk 18]
```diff
@@ -167,9 +166,9 @@ public class EventDataForm extends AbstractEditForm<EventDto> {
 	private final boolean inJurisdiction;
 	private List<UserReferenceDto> regionEventResponsibles = new ArrayList<>();
 	private List<UserReferenceDto> districtEventResponsibles = new ArrayList<>();
-	private EpidemiologicalEvidenceCheckBoxTree epidemiologicalEvidenceCheckBoxTree;
-	private LaboratoryDiagnosticEvidenceCheckBoxTree laboratoryDiagnosticEvidenceCheckBoxTree;
 	private LocationEditForm locationForm;
+	private CheckBoxTreeUpdated<EpidemiologicalEvidenceDetail> epidemiologicalEvidenceCheckBoxTreeUpdated;
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataForm.java:170]: please convert these fields to local variable

File: sormas-ui/src/main/java/de/symeda/sormas/ui/samples/environmentsample/EnvironmentSampleEditForm.java [hunk 19]
```diff
@@ -287,40 +284,24 @@ private void disableFieldsBasedOnRights(EnvironmentSampleDto sample) {
...
-		getValue().setWeatherConditions(weatherConditionCheckBoxTree.getValues());
+		getValue().setWeatherConditions(weatherConditionCheckBoxTreeUpdated.getValue());
 	}
 
 	@Override
 	public void setValue(EnvironmentSampleDto newFieldValue) throws ReadOnlyException, Converter.ConversionException {
 		super.setValue(newFieldValue);
-		weatherConditionCheckBoxTree.setValues(newFieldValue.getWeatherConditions());
-		weatherConditionCheckBoxTree.initCheckboxes();
+		weatherConditionCheckBoxTreeUpdated.setValue(newFieldValue.getWeatherConditions());
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/samples/environmentsample/EnvironmentSampleEditForm.java:300]: not needed

File: sormas-ui/src/main/java/de/symeda/sormas/ui/samples/environmentsample/EnvironmentSampleEditForm.java [hunk 20]
```diff
@@ -107,7 +104,7 @@ public class EnvironmentSampleEditForm extends AbstractEditForm<EnvironmentSampl
 		EnvironmentSampleDto.LAB_SAMPLE_ID,
 		EnvironmentSampleDto.SPECIMEN_CONDITION);
 
-	private CheckBoxTree<WeatherCondition> weatherConditionCheckBoxTree;
+	private CheckBoxTreeUpdated<WeatherCondition> weatherConditionCheckBoxTreeUpdated;
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/samples/environmentsample/EnvironmentSampleEditForm.java:107]: can be converted to local variable

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java [hunk 21]
```diff
@@ -0,0 +1,249 @@
...
+	private Function<ENUM, ? extends Enum> groupProvider;
+	private Class<? extends Enum> parentGroup;
+	private boolean settingToggles = false;
+	private int columns;
+
+	public CheckBoxTreeUpdated() {
+
+	}
+
+	public Map<ENUM, CheckBox> getEnumToggles() {
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java:47]: probably not needed

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java [hunk 22]
```diff
@@ -0,0 +1,249 @@
...
+			if (groupProvider == null) {
+				checkBoxTreeLayout = new VerticalLayout();
+				checkBoxTreeLayout.setMargin(false);
+				checkBoxTreeLayout.setSpacing(false);
+				checkBoxTreeLayout.setWidth(100, Sizeable.Unit.PERCENTAGE);
+				addCheckBoxes();
+				final MarginInfo marginInfo = new MarginInfo(false, false, true, false);
+				checkBoxTreeLayout.setMargin(marginInfo);
+			} else {
+				checkBoxTreeLayoutForGroups = new HorizontalLayout();
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java:64]: rename to `groupLayout` and the othe one to `checkboxLayout` to be shorter

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java (hunk 7 above)
Comment (leventegal-she) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java:102]: not resolved

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java [hunk 23]
```diff
@@ -0,0 +1,249 @@
...
+			final VerticalLayout e = new VerticalLayout();
+			e.setMargin(false);
+			e.setSpacing(false);
+			columnList.add(e);
+		}
+
+		AtomicInteger currentColumn = new AtomicInteger();
+		currentColumn.set(0);
+
+		Arrays.stream(parentGroup.getEnumConstants()).forEach(enumListEntry -> {
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java:126]: rewrite to indexed for cycle and avoid using `AtomicInteger currentColumn`

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java [hunk 24]
```diff
@@ -0,0 +1,249 @@
...
+
+		if (checkBoxTreeLayout != null) {
+			return checkBoxTreeLayout;
+		}
+
+		return checkBoxTreeLayoutForGroups;
+	}
+
+	private void setToggleValues() {
+		settingToggles = true;
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java:94]: changing `settingToggles` should be done in the `setToggleValues(values)` method

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java [hunk 25]
```diff
@@ -0,0 +1,249 @@
...
+import com.vaadin.shared.ui.MarginInfo;
+import com.vaadin.ui.Component;
+import com.vaadin.ui.HorizontalLayout;
+import com.vaadin.ui.Label;
+import com.vaadin.ui.VerticalLayout;
+import com.vaadin.v7.data.util.converter.Converter;
+import com.vaadin.v7.ui.CheckBox;
+import com.vaadin.v7.ui.CustomField;
+
+public class CheckBoxTreeUpdated<ENUM extends Enum<?>> extends CustomField<Map<ENUM, Boolean>> {
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java:25]: please rename to `CheckBoxTreeField`, and renam all variables of this type to not hva `updated` in their name

**Review by leventegal-she — CHANGES_REQUESTED** [review]

File: sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java (hunk 14 above)
Comment (sergiupacurariu) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java:179]: removed

File: sormas-ui/src/main/java/de/symeda/sormas/ui/environment/EnvironmentDataForm.java (hunk 15 above)
Comment (sergiupacurariu) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/environment/EnvironmentDataForm.java:68]: moved the declaration in the method

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13015

File: sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java (hunk 16 above)
Comment (sergiupacurariu) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java:1628]: removed

File: sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java (hunk 17 above)
Comment (sergiupacurariu) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/caze/CaseDataForm.java:312]: moved the variable declaration in the method

File: sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataForm.java (hunk 18 above)
Comment (sergiupacurariu) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/events/EventDataForm.java:170]: moved to local

File: sormas-ui/src/main/java/de/symeda/sormas/ui/samples/environmentsample/EnvironmentSampleEditForm.java (hunk 20 above)
Comment (sergiupacurariu) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/samples/environmentsample/EnvironmentSampleEditForm.java:107]: cannot be converted since it is used in a different method on Disabling and Enabling fields

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java (hunk 24 above)
Comment (sergiupacurariu) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java:94]: removed the method and moved the code to setToggleValues

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java (hunk 21 above)
Comment (sergiupacurariu) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java:47]: removed

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java (hunk 22 above)
Comment (sergiupacurariu) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java:64]: renamed

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java (hunk 7 above)
Comment (sergiupacurariu) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java:102]: updated

File: sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java (hunk 23 above)
Comment (sergiupacurariu) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/utils/CheckBoxTreeUpdated.java:126]: rewritten

**Review by leventegal-she — APPROVED** [review]

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13015
