### PR TITLE
Birthdate month does not show "Empty" instead of "confidential" when …

### LINKED ISSUE #13179: Birthdate month does not show "Empty" instead of "confidential" when restrictions apply
### Bug Description

When Data protection right "See personal data" is removed from an user all the fields designed to hide the data should show "Confidential". The field "Birthdate month" shows "empty string" instead. It should show "Confidential" the same way as the other fields.

### Reproduction Steps

1. Remove from the user role you intend to access Sormas with the Data protection right - "See personal data in jurisdiction"
2. Go to Persons and open a person which has birthday added.
3. The fields birthdate month shows "Empty string" and birthdate day shows "Confidential"

### Expected Behavior

Both fields birthdate month and birthdate day should show "Confidential".

### Affected Area(s)

Web app

### SORMAS Version

Sormas 1.99.0

### Android version/Browser

Edge

### User Role(s)

National User

### Server URL

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by sergiupacurariu**
…restrictions apply #13179

Fixes #13179

### CODE REVIEW

File: sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonEditForm.java [hunk 1]
```diff
@@ -296,13 +296,13 @@ protected void addFields() {
 		ComboBox birthDateMonth = addField(PersonDto.BIRTH_DATE_MM, ComboBox.class);
 		// @TODO: Done for nullselection Bug, fixed in Vaadin 7.7.3
 		birthDateMonth.setNullSelectionAllowed(true);
-		birthDateMonth.addItems(DateHelper.getMonthsInYear());
-		birthDateMonth.setPageLength(12);
+//		birthDateMonth.addItems(DateHelper.getMonthsInYear());
```
Comment (leventegal-she) [inline sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonEditForm.java:299]: Please delete the commented code

**Review by leventegal-she — CHANGES_REQUESTED** [review]

File: sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonEditForm.java (hunk 1 above)
Comment (sergiupacurariu) [reply sormas-ui/src/main/java/de/symeda/sormas/ui/person/PersonEditForm.java]: removed the commented code

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=13180
