### PR TITLE
#12355 - Core entities that are obsolete (archived/soft deleted) are …

### LINKED ISSUE #12355: Environment entities that are obsolete (archived/soft deleted) are not removed from the mobile app
### Bug Description

Environment entities that are obsolete (archived/soft deleted) are not removed from the mobile app by the logic that removes with the synchronization the other obsolete entities.
image

### Reproduction Steps

1. Configure the 149 line from SynchronizaDataAsync to look like the screenshot above;
2. Save the changes and start the mobile app;
3. Log in with a user that has access to the Environment Directory;
4. Trigger a synchronization;
5. Observe that all environment entities are displayed in the mobile app, regardless of whether they are active, archived, or deleted.

### Expected Behavior

The environment entities that are archived or soft deleted should be removed from the mobile app.

### Affected Area(s)

Android app

### SORMAS Version

1.87.0

### Android version/Browser

Chrome, Android Studio

### User Role(s)

Admin+NatUser, Default Environmental Surveillance User

### Server URL

local machine 

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by sergiupacurariu**
…not removed from the mobile app

Fixes #12355

### CODE REVIEW

File: sormas-app/app/src/main/java/de/symeda/sormas/app/rest/SynchronizeDataAsync.java [hunk 1]
```diff
@@ -178,6 +178,7 @@ protected Void doInBackground(Void... params) {
 				// Pull changed data and push existing data that has been changed on the mobile device
 				syncCallbacks.ifPresent(c -> c.getUpdateSynchronizationStepCallback().accept(SynchronizationDialog.SynchronizationStep.SYNCHRONIZE));
 				synchronizeChangedData();
+				pushNewPullMissingAndDeleteInvalidData();
```
Comment (MateStrysewske) [inline sormas-app/app/src/main/java/de/symeda/sormas/app/rest/SynchronizeDataAsync.java:181]: This is not an appropriate solution as this method should not be called when synchronizing only changes; it's meant to be used when doing a complete sync, e.g. after a previous sync has failed or when doing the initial sync after logging in. The logic here has to remain the same, i.e. only when it's been 24 hours since we last removed obsolete data, we do it by calling pullAndRemoveObsoleteUuidsSince.

**Review by MateStrysewske — CHANGES_REQUESTED** [review]

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12489

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12489

File: sormas-app/app/src/main/java/de/symeda/sormas/app/rest/SynchronizeDataAsync.java (hunk 1 above)
Comment (sergiupacurariu) [reply sormas-app/app/src/main/java/de/symeda/sormas/app/rest/SynchronizeDataAsync.java]: the ticket was changed and consists only of fixing the environment entities that are obsolete (archived/soft deleted) and that are not removed from the mobile app. The synchronization issue related to the jurisdiction change of core entities will be dealt with in a different ticket #12503.

**Review by MateStrysewske — APPROVED** [review]
