### PR TITLE
#12794 - The same event participant should not be allowed to be selected

### LINKED ISSUE #12794: The same person can be added multiple times as event participant to the same event via the mobile app
### Bug Description

In the mobile app via the regular create event participant flow, via the mobile app 'line listing' of event participants and via linking events to existing cases and contacts, the same person can be added multiple times as event participant to the same event.

### Reproduction Steps

I: Via the regular create event participant flow:
1. Log into the mobile app with a Default Surveillance Officer;
2. Open an existing event that you have access to;
3. Open the 'Event Participants' tab and click on the pencil icon to enter edit mode;
4. Then click on the + icon to add a new event participant;
5. Fill in the mandatory information and save;
6. Then navigate again on the same event to the 'Event participants' tab
7. Click to add another event participant;
8. Write in the form the exact same data as at step 5 and click to save;
9. In the 'Pick or create person' select the existing person and click 'Select';
Actual behavior: The same person is now listed twice as event participant to the same event. After sync, this is also visible in the web app.

II: Via the mobile app 'line listing' ('Use rapid event participant entry')
1. Log into the mobile app with a Default Surveillance Officer;
2. Open an existing event that you have access to;
3. Open the 'Event Participants' tab and click on the pencil icon to enter edit mode;
4. Then click on the + icon to add a new event participant;
5. Click on the checkbox 'Use rapid event participant entry';
6. Fill in the mandatory information and save;
7. In the next form, add again the exact same information as for the previous event participant and save;
8. In the 'Pick or create person' select the existing person and click 'Select';
9. Navigate back to the event and observe the list of participants.
Actual behavior: The same person is now listed as event participant to the same event.   After sync, this is also visible in the web app.

III: Via linking an event to a case or contact 
1. Log into the web app with a Default Surveillance Officer;
2. Open an existing event that you have access to;
3. Add a new event participant to that event and save;
6. Then navigate to the persons directory and look for the person created at step 3;
7. Create a case for that person;
8. Log in the mobile app with the same Default Surveillance Officer and sync everything;
9. Open the event used at step 2 and navigate to the 'Event participants' tab;
10. Click on the pencil icon to enable editing and then on the + to create a new event participant;
11. In the form, enter the exact same data as at step 3 and save;
12. In the pick or create person select the existing person and click 'Select';
Actual behavior: The same person is now listed as event participant to the same event.   After sync, this is also visible in the web app.

IV: Via linking an event to a case or contact 
1. Log into the web app with a Default Surveillance Officer;
2. Open an existing event that you have access to;
3. Add a new event participant to that event and save;
6. Then navigate to the persons directory and look for the person created at step 3;
7. Create a case for that person;
8. Log in the mobile app with the same Default Surveillance Officer and sync everything;
9. Open the case created at step 7 and navigate to the 'Case events' tab;
10. Click to add an event and select the event from step 2;
11. Save everything and then navigate to the 'Event participants' tab of the event.
Actual behavior: The same person is now listed as event participant to the same event.   After sync, this is also visible in the web app.

### Expected Behavior

At each of the scenarios, in the moment when the user tries to save an event participant that is for the same person, in the same event, the user should see a pop-up that informs them that the person is already an event participant in the same event, similar to how we have this in the web app. 

Active and archived event participants in the same event should be taken into account.

### Affected Area(s)

Android app

### SORMAS Version

1.92.0, 1.91.0

### Android version/Browser

Android Studio

### User Role(s)

Default Surveillance Officer

### Server URL

local machine

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by carina29**
Fixes #12794

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12843

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12843

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12843

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12843

File: sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseEditActivity.java [hunk 1]
```diff
@@ -352,7 +352,10 @@ private void linkEventToCase() {
 				eventParticipantToSave.setResultingCaseUuid(caze.getUuid());
 				EventParticipantSaver eventParticipantSaver = new EventParticipantSaver(this);
 
-				if (!isEventLinkedToCase(caze, event)) {
+				boolean eventParticipantAlreadyExists =
```
Comment (MateStrysewske) [inline sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseEditActivity.java:355]: Unnecessary variable declaration because it's only used once; please directly call the method in the if clause

File: sormas-app/app/src/main/java/de/symeda/sormas/app/person/SelectOrCreatePersonDialog.java [hunk 2]
```diff
@@ -73,7 +77,26 @@ public static void selectOrCreatePerson(final Person person, final Consumer<Pers
 
 		personDialog.setPositiveCallback(() -> {
 			if (personDialog.getSelectedPerson() != null) {
-				resultConsumer.accept(personDialog.getSelectedPerson());
+				if (ado instanceof Event) {
```
Comment (MateStrysewske) [inline sormas-app/app/src/main/java/de/symeda/sormas/app/person/SelectOrCreatePersonDialog.java:80]: Can be shortened to 

```
if (ado instanceof Event && DatabaseHelper.getEventParticipantDao().eventParticipantAlreadyExists((Event) ado, personDialog.getSelectedPerson()) {
```

Only one else clause necessary this way

File: sormas-app/app/src/main/java/de/symeda/sormas/app/person/SelectOrCreatePersonDialog.java [hunk 3]
```diff
@@ -193,6 +218,11 @@ public void onPropertyChanged(Observable observable, int i) {
 				if (getSelectedPerson() == null) {
 					btnCreate.setVisibility(View.VISIBLE);
 					btnSelect.setVisibility(View.GONE);
+
+					//TODO: View based on tag and the item will be set to false
```
Comment (MateStrysewske) [inline sormas-app/app/src/main/java/de/symeda/sormas/app/person/SelectOrCreatePersonDialog.java:222]: Is this TODO still valid? If yes, why? If no, please remove the comment

**Review by MateStrysewske — CHANGES_REQUESTED** [review]

File: sormas-app/app/src/main/java/de/symeda/sormas/app/person/SelectOrCreatePersonDialog.java (hunk 3 above)
Comment (carina29) [reply sormas-app/app/src/main/java/de/symeda/sormas/app/person/SelectOrCreatePersonDialog.java:222]: No, only forgot there :) I'll delete it

File: sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseEditActivity.java (hunk 1 above)
Comment (carina29) [reply sormas-app/app/src/main/java/de/symeda/sormas/app/caze/edit/CaseEditActivity.java:355]: yes, I've used it only to debug easier, I'll delete the declaration

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12843

**Review by MateStrysewske — CHANGES_REQUESTED** [review]
Found an incorrect workflow:

- Create an event with a specific disease (e.g. COVID-19), and create an event participant for that event
- Create a case of the same disease for the same person
- Go to the "Events" section of the case and try to link the case to the created event

Behaviour: Warning message that this case has already been linked to the event appears, which is not true as only the person has been added to the event, but not their case.

Expected Behaviour: Linking the case to the event is successful, but of course no new event participant is created, but the existing person in the event is used instead. If the user tries again to link the same event (after successfully linking the case once), the warning message is displayed.

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12843

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12843

**Review by MateStrysewske — APPROVED** [review]
