### PR TITLE
#12566 - Task synchronization on Android pulls tasks not related with…

### LINKED ISSUE #12566: Task synchronization on Android pulls tasks not related with the user's jurisdiction
### Bug Description

 The synchronization flow pulls all the existing tasks from the server

### Reproduction Steps

1. Login with a surveillance officer on the Android app which has just a very small amount of cases, contacts etc
2. Synchronize
3. Check how many tasks are synchronized. 
4. Tasks linked to cases from different jurisdictions are synchronized

The same behavior can be seen when the Tasks grid is accessed from the web app.
...

### Expected Behavior

Only tasks that are related to core entities from user jurisdiction should be synchronized.

In the web app, Tasks grid should show only tasks that are related to core entities in jurisdiction.

### Affected Area(s)

Web app, Android app

### SORMAS Version

SORMAS 1.89.0

### Android version/Browser

Chrome

### User Role(s)

Surveillance officer

### Server URL

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by sergiupacurariu**
… the user's jurisdiction

Fixes #12566

### CODE REVIEW

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12621

**Review by MateStrysewske — CHANGES_REQUESTED** [review]
Problem is not fixed for me, at least not fully; environment officers still pull tasks related to all/a lot of other entities that they don't have access to.

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12621

File: sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserService.java [hunk 1]
```diff
@@ -715,7 +715,10 @@ public Predicate createCurrentUserJurisdictionFilter(CriteriaBuilder cb, From<?,
 		if (hasRight(UserRight.SEE_PERSONAL_DATA_OUTSIDE_JURISDICTION)) {
 			return cb.conjunction();
 		}
+		return createCurrentUserJurisdictionFilterForTasks(cb, from);
+	}
 
+	public Predicate createCurrentUserJurisdictionFilterForTasks(CriteriaBuilder cb, From<?, User> from) {
```
Comment (MateStrysewske) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserService.java:721]: I'd like these two methods to be refactored, because the content of this method doesn't really have anything to do with tasks; my suggestion would be to call this method "createCurrentUserJurisdictionFilter", and remove the method above because it's only used in one place anyway; instead, move its content to the place where it's currently used

**Review by MateStrysewske — CHANGES_REQUESTED** [review]
Seems to work fine; just one change request in terms of code readability

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12621

File: sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserService.java (hunk 1 above)
Comment (sergiupacurariu) [reply sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserService.java]: changed

File: sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserService.java [hunk 2]
```diff
@@ -290,8 +290,12 @@ public List<UserReference> getUserReferences(
 			userEntityJoinUsed = true;
 		}
 		if (filterByJurisdiction) {
-			filter = CriteriaBuilderHelper.and(cb, filter, createCurrentUserJurisdictionFilter(cb, userRoot));
-			userEntityJoinUsed = true;
+			if (hasRight(UserRight.SEE_PERSONAL_DATA_OUTSIDE_JURISDICTION)) {
```
Comment (MateStrysewske) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserService.java:293]: Actually, the conjunction stuff is probably pretty unnecessary; you can shorten this section to

```
if (!hasRight(...)) {
  filter = CriteriaBuilderHelper.and(cb, filter, createCurrentUserJurisdictionFilter(....));
  ...
}
```

**Review by MateStrysewske — CHANGES_REQUESTED** [review]

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12621

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12621

File: sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserService.java [hunk 3]
```diff
@@ -289,12 +273,12 @@ public List<UserReference> getUserReferences(
 			filter = CriteriaBuilderHelper.and(cb, filter, districtFilter);
 			userEntityJoinUsed = true;
 		}
-		if (filterByJurisdiction) {
-			if (!hasRight(UserRight.SEE_PERSONAL_DATA_OUTSIDE_JURISDICTION)) {
-				filter = CriteriaBuilderHelper.and(cb, filter, createCurrentUserJurisdictionFilter(cb, userRoot));
-				userEntityJoinUsed = true;
-			}
+//		if (filterByJurisdiction) {
```
Comment (MateStrysewske) [inline sormas-backend/src/main/java/de/symeda/sormas/backend/user/UserService.java:276]: Remove the commented code; you can merge the PR afterwards :)

**Review by MateStrysewske — CHANGES_REQUESTED** [review]

**Comment by sormas-vitagroup** [comment]
SonarCloud analysis: https://sonarcloud.io/dashboard?id=SORMAS-Project&pullRequest=12621
